# Generated by Django 6.1 on 2026-09-19 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_course_owner_lesson_owner'),
        ('lms', '0002_subscription'),
    ]

    operations = [
    ]
